server:
  port: 8070
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false # 컨피그 서버가 유레카 서비스에 등록되지 않도록 지시한다.
    fetchRegistry: false # 컨피그 서버가 캐시 레지스트리 정보를 로컬에 캐시하지 않도록 지시한다.
    serviceUrl:
      defaultZone:  # 서비스 URL을 제공한다.
        http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 30000 # 서버가 요청을 받기 전 초기 대기 시간 설정